services:
  - type: web
    name: bike-marketplace-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: VEHICLES_PERSISTENCE
        value: firestore
      - key: VEHICLES_COLLECTION
        value: vehicles
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
